name: CI (Lint & Test)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-lint-and-test:
    name: Backend Lint & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: simulatorV1/python_backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        run: uv python install 3.12

      - name: Install Python Dependencies
        run: uv sync

      - name: Check Format (Ruff)
        run: uv run ruff format --check .

      - name: Lint (Ruff)
        run: uv run ruff check .

      - name: Run Tests (Unittest)
        run: uv run python -m unittest discover

  site-vitrine-lint:
    name: Site Vitrine Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site-vitrine 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24 '

      - name: Install Dependencies
        run: npm ci

      - name: Lint Frontend
        run: npm run lint